[package]
name = "entity_store_code_gen"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
itertools = "0.7"
tera = "0.10"
rustfmt = "0.9"
