//! Library to simplify using code generated by
//! [entity_store_code_gen](https://crates.io/crates/entity_store_code_gen).
extern crate serde;
#[macro_use] extern crate serde_derive;

// handy re-exports
pub extern crate direction;
pub extern crate num;
pub extern crate grid_2d;

mod neighbour_count;
mod id_allocator;

pub use self::neighbour_count::NeighbourCount;
pub use self::id_allocator::IdAllocator;

#[macro_export]
macro_rules! include_entity_store {
    ($filename:expr) => {
        include!(concat!(env!("OUT_DIR"), concat!("/", $filename)));
    }
}
